name: ridefast
description: "A Riding app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  pinput: ^4.0.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  dio: ^5.4.1
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.0.0 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env # Add this line